spring:
  application:
    name: finanzas-app
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:1209600000}
